cursor = '<CURSOR>'
port = 8123
proxy = "http://localhost:2023"

[[models]]
name = 'fitten_code'
type = 'open_ai'
api = ''
model = ''
key = ''
username = 'xxxxxx'
password = 'xxxxxx'

[[models]]
name = 'longcat'
type = 'open_ai'
api = 'https://api.longcat.chat/openai/v1/chat/completions'
model = 'LongCat-Flash-Chat'
key = 'xxxxxx'
username = ''
password = ''

[[models]]
name = 'qwen'
type = 'open_ai'
api = 'https://api-inference.modelscope.cn/v1/chat/completions'
model = 'Qwen/Qwen3-Coder-480B-A35B-Instruct'
key = 'xxxxxx'
username = ''
password = ''

[[models]]
name = 'qwen2'
type = 'open_ai'
api = 'https://api-inference.modelscope.cn/v1/chat/completions'
model = 'Qwen/Qwen2.5-Coder-32B-Instruct'
key = 'xxxxxx'
username = ''
password = ''

[[models]]
name = 'qwen2.5'
type = 'open_ai'
api = 'https://api-inference.modelscope.cn/v1/chat/completions'
model = 'Qwen/Qwen2.5-72B-Instruct'
key = 'xxxxxx'
username = ''
password = ''

[[models]]
name = 'gemini'
type = 'open_ai'
api = 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions'
model = 'gemini-2.5-flash'
key = 'xxxxxx'
username = ''
password = ''
use_proxy=true
